travis:
  secure:
    BINSTAR_TOKEN: GRBspn/uZhTRs0AYq0lWcpXkSZLPbEjU5PqIKH9cAPY3PWDGdBLjZ09UwBD9FADEk6SKoDAVS4mjl+HE3QlM9eGNjB7oqdt+VQFT2atK/QAefAbg6gICe9ouMAc2sbumpTiTeaWfLOw5OThsJmIZvGtK6uvsno7hJN/I4TA87EJdG0SsMX60sH2N5yJBmRKcWBLJLhkLzDhokNc+h4bU56KF87UJncRcKX4oAyWCgCzNWy93FDgqgwsUnV3KukJnEdUvcIxfuYyXYb2o4N8GMbvzgRQD9GGV3JmcQl7crqZs0xNkpsagfPsoZ+tU749yI9mCL3a+XU0huwH2eWZh0EXHA8lD7DYmLRAKN14knAXVJO2TuzpN4OG7x0AXnECLpaJJ09Tl2B0LX+pigVQoYdKmyT1gnuHtLYe7tC5qg6qE8BB5rCHYnUd59pEKHoNwCfUsH5pPiEsa+XO6x9Q7jxc8SQ8KAz6SZUlCyMSd9f/unPZV0Al7lB9yIQHND1coODcNKObsScnIV1/2L7IRSiwZpdAQZXLc/h2eBf0LLDESSSQlknhZtlRc2abhEgAVJGgaLv8ZI8s9neCBF5wSp8mfFO55PInzaye0tEG9CPZOtErUhHJdWif/dDePunsy8EmxSeAlVkjw0TkRTEcU2TlF/HTVOfrk6ztcXynrYfU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
