travis:
  secure:
    BINSTAR_TOKEN: E9WXo1FDkgd3rZT/6cMGjIlEEmtIFRfrk7TRJtEbxmMRvP1eIb0ae9POUJBO5CQMS7QUd9Wtgc+o2uaYoqfJXd1pR1ydl0VQC/IeNCHNINR/n5pb7Cg/uNkvyrTZEafZYm/oWmGab9flgEEWTWOLMMSeKlzkYGMRWcAjhvMJmFrMeyTRCQcFkNATdF/VTlLeprXUn0uedX1SKJf6JV9kbop3+lvpoq5O5omIP8AYHjxY3lKWY8KpkjHI97lPz3WosKOJnS6Q0q33+manbQF8BqWmjnSOoZO8WFBAmn+/qmx7q52EvXqabTm5gtgn/PEvt0Uyr9oqdnwqUZmfpQczXQaCf0e901YQltFyzFVuWV0O8htJQmAok/JCYMkyA2uYjLurezDdY4uGZmdTFp8G1qiJX0unnDapy4khqlZyrA8qYS6bYbrvclJMuH7S4d51lSOhFdneyhgGUb60FWfXjykZpYIZBrOJKW2ORf82C6grRQVMuKfpYlU8arQVEbOWvR5s23hBK9kkynRcBUfB+nPNLpfQ8dD41TYvPfjhoYywAjUZOwXAOsHRJLzCqKaRXOEKzMa+nRVMtPgWK2tiDbMIVp6Ez0YnXq0fczevr5TUnujLy8dlSQrh81KmGIPTOaOsNr4FX+8v9u7eOcpsgE1Vm/Z7CgHI5VCJy+Fcjzg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
